version: '3.7'
services:
    php-fpm:
        build:
            args:
                user: developer
                uid: 1000
            context: docker/php-fpm
        volumes:
            - "./:/var/www"
    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        restart: always
        environment:
            POSTGRES_USER: "database"
            POSTGRES_PASSWORD: "database"
            POSTGRES_DB: "database"
